[package]
name = "kingdom-royale-maid"
version = "0.1.0"
authors = ["RealKC <dumitru0mitca@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros", "signal", "blocking"] }
futures = "0.3"
reqwest = "0.10.8"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

itertools = "0.9"
once_cell = "1.4.1"
rand = "0.7.3"
typemap_rev = "0.1.3"

rust-embed = { version = "5.6.0", features = ["debug-embed"] }
serde_json = "1.0"

dotenv = "0.15"
image = "0.23.10"

humansize = "1.1"
chrono = "0.4"
[dependencies.procfs]
# path = "../procfs"
git = "https://github.com/RealKC/procfs"
branch = "feature/smaps"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
# version = "0.9"
features = ["collector"]