[package]
name = "kingdom-royale-maid"
version = "0.1.0"
authors = ["RealKC <dumitru0mitca@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros", "signal"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
rand = "0.7.3"
once_cell = "1.4.1"
typemap_rev = "0.1.3"
itertools = "0.9"
reqwest = "0.10.8"
image = "0.23.10"
rust-embed = { version = "5.6.0", features = ["debug-embed"] }

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"